### PR TITLE
Update Ecto.Repo calls to work with Ecto 3.8

### PR DESCRIPTION
**Pull request by edgurgel**
Hi there! Thanks for maintaining this great library.

While trying to use ExAudit with Ecto 3.8 I noticed that it wasn't working as intended so I had to do the changes I'm submitting as part of this PR.

Options are now a tuple with adapter metadata instead of just the repo options. I think it was first introduced here: https://github.com/elixir-ecto/ecto/commit/0cf1800056fb30a4fdef7277fe6d27cac8567770

Let me know if I should change it to do something else. Cheers!

### CODE REVIEW

**Comment by tuomohopia** [comment]
@narrowtux Any progress getting this reviewed and merged? `ex_audit` isn't compatible with newer Ecto versions til this gets released.

**Comment by atavistock** [comment]
@narrowtux Is this project still maintained?

**Comment by ambuznego** [comment]
@narrowtux Can you check this out when you get a chance? I would love to be able to use this library. 🙏

**Comment by bumbus** [comment]
> @narrowtux Can you check this out when you get a chance? I would love to be able to use this library. 🙏

This would be great, it fixes my issue 👯 
https://github.com/ZennerIoT/ex_audit/issues/93

**Comment by rohfosho** [comment]
@narrowtux Any updates on this? Is this library still maintained?

**Comment by edgurgel** [comment]
Thanks, @narrowtux !

**Pull request merged**
