### PR TITLE
[WIP] Ecto 3.1

### PR DESCRIPTION
**Pull request by narrowtux**
This PR builds upon #9, but adds support for Ecto 3.1, which changed repo internals again.

### CODE REVIEW

**Comment by narrowtux** [comment]
As all the tests are now working, I think some internal changes have been made to ecto 3.1 that allow tracking of changed assocs like we used to do in Ecto 2.

**Comment by simonprev** [comment]
> As all the tests are now working, I think some internal changes have been made to ecto 3.1 that allow tracking of changed assocs like we used to do in Ecto 2.

This is awesome! Looks like the association code has changed to use the repo instead of applying action on `Ecto.Repo.Schema`.

image

**Comment by narrowtux** [comment]
I can imagine why, they introduced a new argument for all the repo functions that's part of the dynamic repo feature. You'd have to touch the entire codebase to pass this name argument to everything.

Good for us!

**Comment by narrowtux** [comment]
Ecto 3.1.1 released yesterday which changed things again - update incoming

**Comment by narrowtux** [comment]
manually merged

**Pull request closed without merging**
