### PR TITLE
Add missing Ecto features like setting default_options/1

### LINKED ISSUE #74: default_options/1 can't be overridden
Hello,

I've defined in `MyApp.Repo` the function `default_options/1`. Unfortunately `ExAudit` prevents overriding that function. At least it's not used. When I replace

```elixir
    defmodule MyApp.Repo  do
      use ExAudit.Repo
```

by 

```elixir
    defmodule MyApp.Repo do
      use Ecto.Repo
```
it's working correctly.

Moreover when compiling the ExAudit dependency I get `warning: conflicting behaviours found. function default_options/1 is required by Ecto.Repo and ExAudit.Repo (in module MyApp.Repo)`.

### PR DESCRIPTION
**Pull request by MMore**
Moreover this adds missing Ecto functions like `aggregate` and `reload`. 

resolves #74

### CODE REVIEW

**Comment by AndriiKlymchuk** [comment]
Hello @MMore. Why do you use edge branch instead of master? Looks like edge is quite outdated right now.

**Comment by MMore** [comment]
@AndrewKlymchuk Well, initially I did my changes on the 14th of June where `master` was used for older **Ecto** versions. `edge` was for newer ones. Obviously @narrowtux merged `edge` into `master` 3 days later (https://github.com/ZennerIoT/ex_audit/commits/master). 🤷‍♂️

**Comment by AndriiKlymchuk** [comment]
@MMore, got it. Could you please update pr? I'm interested in your fix too.

**Comment by MMore** [comment]
Currently I have limited capacity and this one works for me. I will update it when I have the time to do it. But the next weeks are packed already. Feel free to extend it yourself in the meantime.

**Comment by emaiax** [comment]
Hi, @MMore, I hope you're doing well. :)

Would you mind updating your PR with the new changes that are currently in the `master` branch and using it against your PR instead of `edge`?

I'm very interested in your fix, but I'm not being able to use it right now. How can I help you? :)

**Comment by MMore** [comment]
Hi @AndrewKlymchuk and @emaiax,
please see my comment in #74. HTH. Let's see when the maintainer merges #78.

**Pull request closed without merging**
