### PR TITLE
enhancement(schema): Add ability to ignore audit records

### PR DESCRIPTION
**Pull request by jbavari**
There came a case where we needed records to be written for certain tables, but we didn't want all of them, as some would update very frequently. However, certain fields we did want audited. Thus, we needed a way to do frequent updates without auditing, while still being able to audit others.

This PR addresses adding an `ignore_audit` option - which when passed just writes the record, bypassing the audit records from the changeset.

### CODE REVIEW

**Comment by narrowtux** [comment]
This is already here, with exactly the same name for the option, but buried deeper into the code: 

https://github.com/ZennerIoT/ex_audit/blob/master/lib/tracking/tracking.ex#L55

**Comment by jbavari** [comment]
Oh awesome, so if we set earlier in the process `ExAudit.track(ignore_audit: true)`, this will work? Thanks for the heads up, I guess I didn't dig enough.

**Comment by narrowtux** [comment]
No, ExAudit.track puts things into the `ex_audit_custom` field of the opts. 

This flag should work exactly the same way as your PR would make it work, but evaluated deeper in the code, namely just before ExAudit would compare the changes and insert a record about them. 

For example, calling `Repo.update(changeset, ignore_audit: true)` would suffice.

**Comment by narrowtux** [comment]
This is also documented in https://hexdocs.pm/ex_audit/ExAudit.Repo.html#module-shared-options

Thanks for the PR, but as this feature is already in, I'll be closing this.

**Pull request closed without merging**
