### PR TITLE
chore: support ecto 3.5

### LINKED ISSUE #60: Callback Repo.reload missing
The Repo.reload and Repo.reload! callbacks seem to miss:

https://hexdocs.pm/ecto/Ecto.Repo.html#c:reload/2

### PR DESCRIPTION
**Pull request by brunohkbx**
Resolve #60

### CODE REVIEW

**Comment by spapas** [comment]
Hello could the maintainers of the project please merge this PR and add a new release to hex? The latest version of ex_audit is 0.7 which supports ecto 3.2! I've got a bunch of projects with a dependency of ex_audit and I can't upgrade them. 

If it's not going to be merged and released at all then please at least consider telling us so we can fork the project and use our own versions to be able to upgrade ecto!

**Comment by narrowtux** [comment]
I can only merge if I find the time to fully test if everything continues to work. 

However, you can always add `override: true` to the direct dependencies of your own projects where you're using `ex_audit`:

`{:ecto, "~> 3.5", override: true}`

I wouldn't advise going through the trouble of forking the project only to  upgrade a couple dependencies interally, when you can control that in the projects you're using ex_audit in as well.

**Comment by spapas** [comment]
Thank you very much I didn't even know about `override: true`! Yes, you are right this should be perfect for now :)

Kind regards,
Serafeim

**Comment by brunohkbx** [comment]
@narrowtux would you mind publishing a new release? In the current one, `override: true` does not work. So I ended up pointing `ex_audit` to the github repo, like so:
`{:ex_audit, git: "https://github.com/ZennerIoT/ex_audit"},`

**Comment by emaiax** [comment]
@narrowtux sorry to bother you, mate, but is there anything we can do to help you to upgrade the lib?

**Comment by emaiax** [comment]
@narrowtux sorry to bother you, mate, but is there anything we can do to help you to upgrade the lib?

**Comment by narrowtux** [comment]
Closed because I released 0.9 with support for ecto >= 3.0.0.

I think we should only release when new versions of ecto break something. 
Setting `override: true` to the `ecto` and `ecto_sql` dependencies in the mix.exs of the project that uses `ex_audit` should always work.

**Pull request closed without merging**
