### PR TITLE
Store custom_data inside the process dictionary

### PR DESCRIPTION
**Pull request by ibarchenkov**
This PR removes a single-process bottleneck and significantly simplifies the library. One problem is, I couldn't find how to modify a dictionary of another process therefore `ExAudit.track_pid/2` is not implemented. Any ideas how to overcome this problem? Can we allow to break the public API by removing this function?

### CODE REVIEW

**Comment by narrowtux** [comment]
Tracking data for other processes is useful in case you don't control the code that runs the process.

I don't think we can remove it.

I want to question the necessity of the change, however. There is another way to remove the bottleneck in case it actually gets too slow for your app because the tracking process is swamped with messages.

Since the actual data is stored in an ets table, it could be accessed from anywhere. The process would still be there to monitor the pids being tracked so their data can be cleaned up when they terminate.

Then, the only messages for the tracking process would be those asking it to monitor the new PID. These messages can be sent as a cast to completely avoid waiting for the reply of the process.

**Comment by ibarchenkov** [comment]
There's another issue with the current implementation: `ExAudit.track_pid/2` doesn't work as expected for processes on remote nodes. Consider this example:
* Node A and Node B are connected in a cluster. There's one `:track_by_pid` ETS table on both nodes.
* Node A calls `ExAudit.track_pid(pid_on_nodeB, foo: "bar")` and stores the data in its local table.
* The process on Node B when inserting a new Version calls `ExAudit.CustomData.get()` which reads the data from the table on Node B and gets `[]`.

**Comment by narrowtux** [comment]
> single-process bottleneck

> `ExAudit.track_pid/2` doesn't work as expected for processes on remote nodes

Did these problems occur in your app? IMO we can solve both without removing track_pid.

**Comment by ibarchenkov** [comment]
> Did these problems occur in your app? IMO we can solve both without removing track_pid.

Single-process bottleneck is a serious drawback that blocks me from using this library in production.
The second issue with tracking remote processes I think is quite tricky to solve without introducing unnecessary complexity to the lib. Maybe it'd be simpler to add `track_local_pid/2` and deprecate `track_pid/2` or explicitly document that `track_pid/2` works only with local processes.
Anyway, it's up to you to decide. Let me know if I can help.

**Comment by narrowtux** [comment]
> Single-process bottleneck is a serious drawback that blocks me from using this library in production.

I've offered suggestions on how to mitigate this without needing to drop a feature. 

For example, the public `:ets` table that is spawned by that process can be used from outside of the process, so the only thing the process needs to do is monitor the pids that are tracked to clean up the ets once they terminate.

`:ets` does very well in terms of concurrent read access.

> The second issue with tracking remove processes I think is quite tricky to solve without introducing unnecessary complexity to the lib.

Tracking terminating processes is very simple in Elixir, and it's also already implemented in this library.

I can draft up some changes that should resolve your initial issues with the single-process bottleneck (TBH I've never perceived that process to be a limiting factor in our heavily-used production app).

You are of course welcome to submit PRs but please understand that I can't accept them if they remove functions without a period of deprecation.

**Pull request closed without merging**
