### PR TITLE
Upgrade ecto to 3.0.7 and add ecto_sql package

### PR DESCRIPTION
**Pull request by vasuadari**
Updated package to work with `ecto 3.0.7`. It doesn't support tracking versions for associations.

It requires existing apps to modify column type of `recorded_at` from `utc_datetime` to `utc_datetime_usec`.

Closes #12

### CODE REVIEW

**Comment by vasuadari** [comment]
@ZennerIoT @narrowtux Need your help in supporting version tracking for associations on inserts.

**Comment by vasuadari** [comment]
**Failing Tests**

```elixir
  1) test should track cascading deletions (before they happen) (AssocTest)
     test/assoc_test.exs:32
     Assertion with == failed
     code:  assert length(versions) == 6
     left:  3
     right: 6
     stacktrace:
       test/assoc_test.exs:65: (test)

 2) test comment lifecycle tracked (AssocTest)
     test/assoc_test.exs:8
     ** (MatchError) no match of right hand side value: []
     code: [%{actor_id: actor_id}] = comment_history = Repo.history(comment)
     stacktrace:
       test/assoc_test.exs:27: (test)

```

**Comment by narrowtux** [comment]
https://github.com/ZennerIoT/ex_audit/pull/9 we already have an ongoing PR here with the same problem

**Comment by vasuadari** [comment]
@narrowtux I didn't see any issue created for it after creating a PR noticed it 🤕. Anyway, currently i'm pointing to this branch until one of the PR gets merged. Our app doesn't need associations to be tracked as of now.

**Comment by narrowtux** [comment]
no problem. is it cool if I close this so there's no confusion?

**Comment by vasuadari** [comment]
Sure. I'm closing this.

**Pull request closed without merging**
